module.exports = [
  {
    id: 1,
    title: "Roasted Cauliflower & Garlic Dip",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    image:"https://images.squarespace-cdn.com/content/v1/5ced3ca71bd8b30001701f6b/1561658953505-IK4EXXTMJ1B83M6R8K9I/download+%284%29.jpeg?format=500w",
    author:"",
    blog_id: 2,
  },
  {
    id: 2,
    title: "Broiled Salmon with Spring Onion Risotto",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    image:"https://images.squarespace-cdn.com/content/v1/5ced3ca71bd8b30001701f6b/1561658899958-ABKXTIQDV0D0TM363SNH/download+%283%29.jpeg?format=500w",
    author:"",
    blog_id: 2,
  },
  {
    id: 3,
    title: "Make Your Adventure Sound Epic",
    content: "Chris and I bicycled across the San Rafael Swell, from north to south. It was a little under 60 miles, and we took a couple days to do it. It was more gravel-grinding than actual mountain biking, but I thought it was fun. I ran out of water a couple times on the second day before we found more, but Chris had enough and gave me some of his. My rear brake also completely fell off my bike near the end of the second day, but I was able to jimmy-rig it with some baling wire and it worked just fine for the last 25 miles. I think I would try to find a different route next time, and take more water for the middle segment. It was a really pretty ride.",
    image:"https://tse3.mm.bing.net/th?id=OIP.tIzr2UDYQAnOhjAAsmDbdgHaEi&pid=Api&P=0&w=292&h=180",
    author:"BY BRENDAN LEONARD SEMI-RAD ",
    blog_id: 1,
  },
  {
    id: 4,
    title: "Adventure Travel Equipment",
    content: "Having the right travel equipment makes all the difference so we’ve tested the best gear to be sure you are fully prepared for your adventure trips.We’ve chosen our equipment for travelling based on price and durability to make sure you’ll have enough spending money for all those other fun activities. With the right gear you can fully enjoy your travel adventures, get around quickly, see as much as possible and have fun!",
    image:"http://1.bp.blogspot.com/-c1HIImqQ3mE/T8z_2Kju4VI/AAAAAAAABZY/Pl9BRIvn0b4/s1600/adventure-wallpaper4.jpg",
    author:"BY BRENDAN LEONARD SEMI-RAD",
    blog_id: 1,
  },
  {
    id: 5,
    title: "What Style is Your House?",
    content: "Whether you're remodeling, adding a second level, or just giving your home some extra curb appeal, knowing the style of your house can help you develop a successful plan. You'll also gain a greater appreciation of the way your house was designed and built.This guide to house styles will help you understand the many variations within the different designs. You can also find architecture guides at your local library or in larger bookstores that will help you identify a particular style or design. Using the original style of your house as a starting point for an exterior makeover is usually the best technique, but, in some cases, mixing styles can energize a design.",
    image:"https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F37%2F2016%2F02%2F15230656%2Fwhite-modern-house-curved-patio-archway-c0a4a3b3.jpg&q=85",
    author:"THE PLUMBETTE",
    blog_id: 3,
  },

  {
    id: 6,
    title: "Property Styling on a Budget: Which Rooms Should be Home Staged?",
    content: "If you’re planning to sell your property, you will no doubt be looking for ways to make your home stand out from the rest in your suburb. Property styling on a budget is achievable and it is key to attracting more buyers.The responsibility of ensuring your property appeals to a potential buyer relies on how you style the property. To ensure your house looks amazing for the listing photos and open home inspections, property styling will be a fundamental step.Homes that undergo property styling will spend less time on the market and reap higher offers, compared to homes that are simply presented ‘as is’.",
    image:"https://www.theplumbette.com.au/wp-content/uploads/2018/08/property-styling-header-768x576.jpg",
    author:"THE PLUMBETTE",
    blog_id: 3,
  },
  {
    id: 7,
    title: "READ MYSTERY BOOKS FOR KIDS",
    content: "I love me a good mystery. I want to be Miss Marple when I grow up and Flavia de Luce is absolutely my best friend in my head. But long before Agatha Christie and Alan Bradley filled my bookshelves, I was a kid enraptured by spies named Harriet and kids living in boxcars. Mystery books for kids are great because they foster logical thinking and deductive reasoning. They’re also just plain fun.Classics like Nancy Drew and the Hardy Boys still have a healthy readership, but the genre has come a long way. There are so many fantastic mystery series and standalone works out there by a diverse mix of authors and illustrators. I’ve compiled a list of 50 mystery books for kids, both new and tried & true. The list spans everything from cake theft capers in picture books to art heist novels for middle grade readers.",
    image:"https://s2982.pcdn.co/wp-content/uploads/2018/06/mystery-books-for-kids.jpg.webp",
    author:"READ MYSTERY BOOKS FOR KIDS",
    blog_id: 4,
  },
  {
    id: 8,
    title: "Visit Spots for Mystery Lovers",
    content: "PUT ON YOUR DEERSTALKER CAP and get out your magnifying glass (or your smartphone, because it’s 2019), it’s mystery time! Part of what makes the world such a wondrous place are the unanswered questions associated with many artifacts and historic locations. Whether it’s a curious contraption from antiquity, or a grimly fascinating unsolved crime, the mysteries of the world keep us guessing, and many of them are tied places you can visit (even if they still refuse to give up their secrets). We recently asked Atlas Obscura readers in our Community forums to tell us about the mysteries that fascinate them, and they led us to some truly enigmatic places.Check out some of our favorite recommendations below, and if you have a mysterious place of your own that you just can’t stop thinking about, head over to our Forums and keep the conversation going. True mysteries might not have easy answers, but you don’t need to be a detective to be fascinated by where they took place.",
    image:"https://assets.atlasobscura.com/article_images/65212/image.jpg",
    author:"BY ERIC GRUNDHAUSER",
    blog_id: 4,
  },
  {
    id: 9,
    title: "THE FILLMORE MINNEAPOLIS",
    content: "We celebrated our Grand Opening in February of 2020 with Grammy Award winner Brandi Carlile who kicked it all off with a 3-night Grand Opening celebration Feb 12-14 in our beautiful state-of-the-art 1850-capacity venue!Signature Fillmore aesthetics, vintage concert posters and local touches will adorn our 36,000 square foot venue when we open the doors to the newest Fillmore in the country. Known for our hospitality, incredible sight lines and warm environment, The Fillmore Minneapolis will proudly carry on a tradition of welcoming guests and treating them like family for years to come.Signature Fillmore aesthetics, vintage concert posters and local touches adorn our 36,000 square foot venue. Known for our hospitality, incredible sight lines and warm environment, The Fillmore Minneapolis proudly carries on a tradition of welcoming guests and treating them like family for years to come.",
    image:"https://mavenprodcontent.blob.core.windows.net/media/FillmoreMPLS/Assets/fillmore-minny-exterior-3.jpg",
    author:"",
    blog_id: 5,
  },
  {
    id: 10,
    title: "The Fillmore Detroit",
    content: "The Fillmore Detroit is a beautiful historic venue located in the heart of Detroit's entertainment district. Originally opened in 1925 as a movie house, this elegant venue has been renovated to offer guests a unique concert and special event experience. As you walk through the grand lobby of The Fillmore Detroit you are embraced by the nostalgia of the original Fillmore chandeliers and the history they represent. Within the theatre, the 80 foot ceiling is flanked by the famous chandeliers as well as a hardwood dance floor. As you walk down memory lane, catch a glimpse of the infamous rock poster wall featuring a small sampling of the endless artists who have graced this magnificent stage. The Fillmore Detroit offers a robust stage presence with audio equipment and visual lighting to match the passion of our visiting performance artists.",
    image:"https://mavenprodcontent.blob.core.windows.net/media/FillmoreDetroit/Assets/Venue%20Info%20Images-Updated/The-Fillmore-Detroit-Theater.jpg",
    author:"",
    blog_id: 5,
  },
];
